apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: graylog
spec:
  ports:
    - name: dbtcp
      protocol: TCP
      port: 27017
    - name: dbudp
      protocol: UDP
      port: 27017
  selector:
    app: mongodb
