apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-volume
  namespace: graylog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
